### ISSUE TITLE
Is it possible to hook in during create-project?

### ISSUE THREAD

**Issue by oxyc** [hirak/prestissimo#103]
I noticed the plugin isn't loaded during `composer create-project` so the first few repository `packages.json` files aren't downloaded in parallel. I'm not familiar with Composer codebase at all, is this a current limitation or is it a possible feature addition in Prestissimo?

**Comment by hirak** [comment]
Yes. The parallel downloading packages.json function exercises only under a specific condition (now).
It's difficult in plugin's layer.

**Comment by oxyc** [comment]
Thanks. At least you 3.0 release yesterday decreased my `composer install` step by 160 sec. Keep up the great work!

**Comment by hirak** [comment]
@oxyc I released prestissimo-0.3.1 yesterday. The parallel downloading enables during `composer create-project`. Please try it!

```bash
$ composer global update hirak/prestissimo
```

**Comment by oxyc** [comment]
Awesome! Haven't done any proper benchmarking but from looking at the output from `-vvv --profile` it looks a lot better now! Thanks again for an amazing project.
