### ISSUE TITLE
The "hirak/prestissimo" plugin was skipped because it requires a Plugin API version ("~1.0.0-alpha10") that does not match your Composer installation

### ISSUE THREAD

**Issue by burzum** [hirak/prestissimo#105]
I just did a `composer selfupdate` 

```sh
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Updating to version 1.1.2 (stable channel).
    Downloading: 100%
Use composer self-update --rollback to return to version 1.0.3
```

and got this when running `composer update`:

> The "hirak/prestissimo" plugin was skipped because it requires a Plugin API version ("~1.0.0-alpha10") that does not match your Composer installation ("1.1.0"). You may need to run composer update with the "--no-plugins" option.

**Comment by xabbuh** [comment]
Looks like you are using an older version ID the plugin and you should update it.

**Comment by burzum** [comment]
True. ;) Thanks.
