### ISSUE TITLE
support composer 1.1.0

### ISSUE THREAD

**Issue by iicmaster** [hirak/prestissimo#116]
today I encounter error 

`The "hirak/prestissimo" plugin was skipped because it requires a Plugin API version ("~1.0.0-alpha10") that does not match your Composer installation ("1.1.0"). You may need to run composer update with the "--no-plugins" option.`

I thought you plugin is already compatible with composer 1.10 just need to adjust the config :)

**Comment by rskuipers** [comment]
@iicmaster Are you sure your plugin is up-to-date?

```bash
$ composer global require "hirak/prestissimo:^0.3"
```

**Comment by hirak** [comment]
Please try re-install.

```bash
$ composer global remove 'hirak/prestissimo'
$ composer global require 'hirak/prestissimo'
```

**Comment by iicmaster** [comment]
issue solved after re-install thanks
