### ISSUE TITLE
Use prestissimo plugin on per-project basis

### ISSUE THREAD

**Issue by martinsik** [hirak/prestissimo#122]
I'm wondering if I can use this plugin without installing it globally. 

I understand it needs to be already downloaded before calling `$ composer install`. Maybe I could set custom project specific `$COMPOSER_HOME` where I'll call `$ composer global require "hirak/prestissimo:^0.3"` and then use the same home directory when calling `$ composer install` (similarly to https://github.com/hirak/prestissimo/issues/71).  
But this will force `composer` to download all dependencies for each project separately because each project will have it's own cache inside its own `$COMPOSER_HOME` which will lead to large waste of disk space. I could delete the cache afterwards but this would prevent Composer from reusing already downloaded packages so the increase of performance won't be that great.

Or is there any other way?

**Comment by hirak** [comment]
@martinsik  I recommend installing this plugin globally.

- Composer plugin installing locally is my troubles.
  - Frequently fails update/install.
  - Once you install it locally, you cannot uninstall freely.
    - need to update `composer.lock`.
- I think composer's cache does not become so big.
  - default `~300MiB`
- You can control cache size by `composer config -g cache-files-ttl xxxxx` or `composer config -g cache-files-maxsize xxxxx`.
  - https://getcomposer.org/doc/06-config.md#cache-files-ttl
