### ISSUE TITLE
Does it helps to speed up reading composer.jsons of required packages?

### ISSUE THREAD

**Issue by Nayjest** [hirak/prestissimo#124]
In my case I had ~200 sec for "composer update" operation (even if no packages updated, just reading  composer.json of all related packages) and have same udate  time after installing this package.

**Comment by hirak** [comment]
@Nayjest If you use `type: vcs` (git, svn, etc.), This plugin will be useless.
Prestissimo is powerless for the git protocol.

Please try `--prefer-dist` option if you use github or gitlab.  It may become fast to download a file using WebAPI.

**Comment by sadortun** [comment]
@hirak Do you plan to implement something for vcs ? It would be quite awesome!

**Comment by hirak** [comment]
@sadortun It is going to be a difficult task. Please do not expect too much and wait.

**Comment by sadortun** [comment]
ehehhehehe ! Ok !! Can you point us in wich direction we should look if we want to submit a PR ?
