### ISSUE TITLE
undefined IO:Verbose

### ISSUE THREAD

**Issue by Zabanya** [hirak/prestissimo#129]
> Fatal error: Undefined class constant 'VERBOSE' in /root/composer/vendor/hirak/prestissimo/src/Prefetcher.php on line 36

I got this error on Bitbucket Pipelines, what am i missing?.
edit: for now i'll use 0.3.4

**Comment by hirak** [comment]
@Zabanya Which version of composer do you use?
Try `composer self-update`. Prestissimo only supports stable version composer (>= 1.0.0) .

`Composer\IO\IOInterface::VERBOSE` is now available from composer version 1.0.0-beta1.
https://github.com/composer/composer/commit/49d7d65933c78e163354c2c580883926f1c8daee

**Comment by Zabanya** [comment]
Composer version 1.0-dev (ecd490b24942590429da64a1ff47c0f14eafc6ac) 2015-12-07 14:30:26
Completed at 2016-11-29T14:23:35Z

too old?, it comes with Bitbucket docker called pipelines. maybe i'll add self-update before installing prestissimo
