### ISSUE TITLE
Can we prefetch if composer.lock exists?

### ISSUE THREAD

**Issue by umpirsky** [hirak/prestissimo#130]
I see prefetch is skipped is `composer.lock` exists https://github.com/hirak/prestissimo/blob/master/src/Plugin.php#L75.

Why?

**Comment by hirak** [comment]
If composer.lock exists and you only need to `composer install`, composer will not communicate with packagist.org.
Therefore, prestissimo does not need to prefetch.

Zip download parallelization is activated regardless of the command, so please be relieved.

**Comment by umpirsky** [comment]
@hirak Thanks!
