### ISSUE TITLE
will it work with a composer.lock?

### ISSUE THREAD

**Issue by cordoval** [hirak/prestissimo#147]
this is on the download part right? the optimization happens on download not on resolving of dependencies right?

**Comment by ypereirareis** [comment]
Hi ! 

Yes !

The download is done in parallel with prestissimo.
So it's useful when installing more than one dep and really performant when installing all deps for the first time.

Have a look at: https://github.com/ypereirareis/docker-composer#composer-vs-prestissimo

Bye !
