### ISSUE TITLE
cannonical docker image with this on it

### ISSUE THREAD

**Issue by cordoval** [hirak/prestissimo#148]
or at least provide the docker run commands to install on top of say a alpine image

**Comment by radmen** [comment]
If you have composer install all that needs to be done is running `composer global require hirak/prestissimo`.

This should be enough

```
RUN composer global require hirak/prestissimo
```

It may be a good idea to add some safety checks with cache clear (to save some space).

```
RUN set -xeu \
    && composer global require hirak/prestissimo \
    && composer clear-cache
```

**Comment by cordoval** [comment]
why the -xeu?

**Comment by radmen** [comment]
From `help set`:

* `-x Print commands and their arguments as they are executed.`
* `-e  Exit immediately if a command exits with a non-zero status.`
* `-u  Treat unset variables as an error when substituting.`

In the example, I've provided `xu` flags which are useless. I've probably used them out of my habit.

**Comment by roquie** [comment]
Try my simple image, which add this feature https://hub.docker.com/r/roquie/composer-parallel/
