### ISSUE TITLE
Possible cache race condition with Satis repositories

### ISSUE THREAD

**Issue by carlosvini** [hirak/prestissimo#150]
First of all thanks for this amazing plugin.

I have used it in development with no problems at all, however I had some problems with simultaneous deployments which seem to result from some kind of race condition and cache misdetection. 
During a simultaneous deployment in 2 folders of the same server and user, one of them went just fine and the other had a dependency installed with an empty folder. So /vendor/mycompany/packagename was just an empty folder.
I have mycompany/packagename on a Satis repository which points to private Github repos, all other dependencies seem to be unaffected.
I'm afraid I don't have more data to provide.
If you ever have the time to look at it, it would be nice. 

Thanks!

**Comment by staabm** [comment]
is presstisimo compatible for use with satis? does it make sense/is it enough to install it on the same node as satis and will this speedup the process?

or is presstisimo only required on the actual node running the composer process, not the one which runs satis as a service?

**Comment by jp7carlos** [comment]
@staabm As far as I can tell Prestissimo works well with Satis repo. Never tried installing it on the Satis server, not sure if it would matter. I installed it where composer is used. My issue was just with 2 simultaneous installs. I had no problems installing only 1 app.
