### ISSUE TITLE
No any change in speed on `composer update`

### ISSUE THREAD

**Issue by OnkelTem** [hirak/prestissimo#151]
Is my understanding correct that it can only speedup downloads while regular running of `composer update` isn't affected?

I'm asking because that's exactly the problem I was trying to get solved: slow `composer update`s. It takes up to 4 minutes on my decent i7 and SSD on a regular (Drupal) project. When viewing the verbose output I see a lot of `Reading path/to/some/json.json from cache`-lines first and it takes half of ages, and then I see that it's rebuilding some SAT — for the rest of ages.

And my tests show that there is no difference in `composer update` operations - with or without this plugin.

**Comment by emirb** [comment]
Possible duplicate of https://github.com/hirak/prestissimo/issues/137, please check [this particular comment](https://github.com/hirak/prestissimo/issues/137#issuecomment-311305887).

**Comment by OnkelTem** [comment]
Oh, yes, you're right, it's a duplicate.

**Comment by emirb** [comment]
Have you checked your curl version? Did the output of composer change at all?

**Comment by OnkelTem** [comment]
> Have you checked your curl version?

```
$ curl --version
curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smtp smtps telnet tftp 
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP
```

> Did the output of composer change at all?

Yes I see now at the beginning of the output a new stuff like:

```
$    1/2:       https://packages.drupal.org/8/drupal/provider-2017-3$b92ea7769b35f2231efd15feb7491394ac80fc2e1fa0d9e971b56addd9848936.json
    2/2:        https://packages.drupal.org/8/drupal/provider-2017-2$ca6c228aa167a0fd60eb5a04969d7915b5e3a0fc8cf617338f9c5559a233a1fc.json
    Finished: success: 2, skipped: 0, failure: 0, total: 2
    1/4:        http://packagist.org/p/provider-2017-07$bc4f3e7010109699b7f8af49d4307a0ba4c7bb382f20a208ac6f44675b466698.json
    2/4:        http://packagist.org/p/provider-latest$32b7ac087a8d732a761440d804d1888f6d20cb482d2ab6e71349ef76843eb8de.json
    3/4:        http://packagist.org/p/provider-2016$248c72f2f4d0b6aba57c9582f7b7a6e5d4b895f75de211365f3bf67e93e66ed4.json
    4/4:        http://packagist.org/p/provider-2017-04$2e961074044b41987fc77d755f82c7314a6996259607c2c4ee41ce4ad43d66cb.json
```
