### ISSUE TITLE
Missing PHP 7.2 support

### ISSUE THREAD

**Issue by finwe** [hirak/prestissimo#155]
After updating composer with plugin installed on PHP 7.2, this error is raised.

```
Loading composer repositories with package information
Updating dependencies (including require-dev)               
    Prefetch start: total: 1

                                                                              
  [ErrorException]                                                            
  count(): Parameter must be an array or an object that implements Countable 
```

Will look into it if I have a bit of spare time.

**Comment by insign** [comment]
I think you should remove all related packs like, php and composer, then reinstall to try again. A fresh install worked fine here.

**Comment by johnroyer** [comment]
I have same problem. But I follow the instruction above, reinstall composer and prestissimo, the problem solved.

----

PHP version: `7.2.0`
composer version: `1.6.1`
prestissimo: `0.3.7`

**Comment by BR0kEN-** [comment]
Unfortunately, the issue persists since the `runningRequests` property of `Hirak\Prestissimo\CurlMulti` may be `null`, and it's not allowed to be passed to `count()`.
