### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by ktomk** [hirak/prestissimo#163]
Just wanted to make this at least a report, albeit the circumstances are rather obscure.

Not only are the circumstances obscure, the setup itself is not ideal, here, composer runs as root inside a
docker container. The situation is not always reproducible but for PHP master. The setup is on Travis:

Travis VM Image with a PHP version (various versions in the matrix). It starts a commandline tool which runs docker images in which prestissimo is globally installed (by root) to speed up a follow-up composer install (sometimes with require / update first).

For PHP Master constantly, for other PHP versions occasionally the composer install operation with prestissimo installed results in:

    Segmentation fault (core dumped)

When I restart the build on Travis it then normally works.

Before integrating prestissimo the builds always worked.

I know this report is kind of not ideal but as it continues to happen I decided to report it at least.

/E: Example builds: 

- https://travis-ci.org/ktomk/pipelines/jobs/326989292#L794
- https://travis-ci.org/ktomk/pipelines/jobs/327007339#L799

**Comment by hirak** [comment]
I don't know. composer and prestissimo are pure PHP program, so I think they rarely cause segmentation fault.

**Comment by ktomk** [comment]
@hirak: Not pushing to keep this issue opened nor to blame prestissimo here, but from what I know it is relatively easy in pure PHP to cause segmentation faults, e.g. some runaway regex pattern via the pcre extension and similar (well technically not the PHP code but the underlying extension which is causing the segmentation fault). Just saying because of your comment. I had more problems recently w/ the build which I think are fixed now, so I might keep record here if I still run over the problem. As this is in the mount + copy test I also suspect this is b/c of the mount and doing file operations there, perhaps w/ prestissimo there is more disk I/O and it's just the mount kicks out here on the kernel level. Or for what it's worth: That build is using a PHP 5.3 docker container, so let's not assume it's really stable.
