### ISSUE TITLE
Package seems to contain suspicious urls

### ISSUE THREAD

**Issue by jrequiroso** [hirak/prestissimo#175]
While installing Laravel, I was wondering why composer was so slow on windows and came across [This thread](https://stackoverflow.com/questions/28436237/why-is-php-composer-so-slow?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa). I went ahead and installed [hirak/prestissimo](https://packagist.org/packages/hirak/prestissimo) via 
> composer global require hirak/prestissimo -vvv

The install was very slow and I was curious why, so I went ahead and selected one of the urls composer was trying to download and found [these lines in the package.](https://i.imgur.com/pzM8sQg.png)

Is this package compromised?

**Comment by Lavoaster** [comment]
It's downloading index files from packagist, so these are just packages on packagist.org with very funky names.

See https://packagist.org/?query=0123-mov

**Comment by jrequiroso** [comment]
I see. Thanks for the quick answer, will close this issue then. 😄
