### ISSUE TITLE
Cannot install below PHP version 7.2

### ISSUE THREAD

**Issue by kozie** [hirak/prestissimo#221]
I first tried installing prestissimo on PHP 7.0 but got an error. I switched (using valet+) to 7.1.33 and got another error, as following:

```$ composer global require hirak/prestissimo
Changed current directory to /Users/XXX/.composer
Using version ^0.3.10 for hirak/prestissimo
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - nategood/httpful 0.3.2 requires php >=7.2 -> your PHP version (7.1.33) does not satisfy that requirement.
    - nategood/httpful 0.3.2 requires php >=7.2 -> your PHP version (7.1.33) does not satisfy that requirement.
    - nategood/httpful 0.3.2 requires php >=7.2 -> your PHP version (7.1.33) does not satisfy that requirement.
    - Installation request for nategood/httpful (locked at 0.3.2) -> satisfiable by nategood/httpful[0.3.2].


Installation failed, reverting ./composer.json to its original content.
```

Seeing the version requirements by prestissimo i should be able to install from `>=5.3` but i'm not able to.

composer version 1.10.5.

Everything is freshly installed so i shouldn't have conflicts with older versions of whatever nor do i have other stuff globally installed with composer.

If you need more info, please let me know.

**Comment by kubawerlos** [comment]
How did you install `nategood/httpful`? With PHP 7.2 or above, right? Switch back to PHP 7.2 and uninstall it.

Or use Composer's dirty hack known as flag `--ignore-platform-reqs`.

**Comment by kozie** [comment]
i can't recall installing anything (on global level) on PHP 7.2. As i stated before, everything is freshly installed.

I did, however, installed it using the flag you mentioned which seem to work like a charm. I did know about the flag but somehow it didn't come into mind 😅.

Thanks tho.

**Comment by kozie** [comment]
i'm leaving this ticket open as i don't think using the flag is a solution. Don't bother closing it anyway if it can't be reproduced.

**Comment by tobiasbaehr** [comment]
This not a problem of this package. You try to install something which require "nategood/httpful" which needs >=7.2 https://github.com/nategood/httpful/blob/master/composer.json#L16

**Comment by kozie** [comment]
Sorry for the late response. It seems that `nategood/httpful` was indeed installed through another packge, namely valet plus.

```bash
$ composer global why nategood/httpful
Changed current directory to /Users/kozie/.composer
weprovide/valet-plus  2.0.0  requires  nategood/httpful (~0.2)
```

So it seems it isn't related to prestissimo in any way. Therefore i'll close this ticket.

Still i think it's strange that installing prestissimo gives the error which i mentioned in my first post related to packages installed for another project. Perhaps i'm missing composer knowledge on that part, though.
