### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by driskell** [hirak/prestissimo#226]
On a very large Magento 2 setup we're seeing for fresh installs the following error when running `composer install`. With `prestissimo` removed it works fine.

```
  [ErrorException]
  fopen(/Users/jason.woods/.composer/cache/files/magento/module-currency-symbol/a88dd237717157a05217e9aec03be4a1eceb0c65.zip): failed to
  open stream: Too many open files
```

We tracked it down to this line:
https://github.com/hirak/prestissimo/blob/master/src/CopyRequest.php#L91

The file is opened during the building of the requests. This means when you've got thousands of packages to download it can hit the file limit even though it's only going to proceed with 10/100 requests at a time.

I guess the best fix is that FP is opened on first call to getCurlOptions instead?

**Comment by vesper8** [comment]
you can also just run this on your CLI first and then it works `ulimit -n 10000`

**Comment by driskell** [comment]
Thanks. Would be great to fix the issue though. It’s on my list to look at and PR but would be great to get some contributor hints if any pass by.

**Comment by driskell** [comment]
I raised a PR that works. It removes need to mess with `ulimit`
