### ISSUE TITLE
does this alter how composer clear-cache works ?

### ISSUE THREAD

**Issue by vesper8** [hirak/prestissimo#229]
I noticed that after running composer clear-cache, if I run composer install it has to download a lot of json files sure but it doesn't appear to actually re-download any of the packages ?? as if they are still cached because of this package. Does this package add an additional layer of cache that composer clear-cache does not remove?

**Comment by spiilmusic** [comment]
It's not a joke, working solution is:
```
composer global remove hirak/prestissimo
```

**Comment by vesper8** [comment]
> It's not a joke, working solution is:
> 
> ```
> composer global remove hirak/prestissimo
> ```

This package was certainly good for many years but with Composer 2 it's not needed anymore and there's really no reason why anyone should not be using Composer 2 at this point
