### ISSUE TITLE
Will this plugin become obsolete with Composer 2?

### ISSUE THREAD

**Issue by back-2-95** [hirak/prestissimo#230]
I see that this question is thrown here and there.

Here are a few issues related:

https://github.com/hirak/prestissimo/pull/223
https://github.com/hirak/prestissimo/issues/164

And the one from Composer where parallel download is added to it:

https://github.com/composer/composer/pull/5293

**Comment by scotself** [comment]
See also #233

**Comment by back-2-95** [comment]
I'd say the answer is "yes".
