### ISSUE TITLE
Error composer global require hirak/prestissimo

### ISSUE THREAD

**Issue by eacevedof** [hirak/prestissimo#243]
running composer global require hirak/prestissimo I get this error:
```
[InvalidArgumentException]                                                                                               
  Package hirak/prestissimo has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version                                                                                                                         
```
- php version:   
    - PHP 7.4.1
- composer version: 
    - Composer version 2.0-dev (2.0-dev+bc31351b5bbbc5d33e916c1e54df3a291c0909b5) 2020-12-15 19:39:50

![Image](https://trello-attachments.s3.amazonaws.com/5fde34b0466fb24a5ccc7328/5fde34c98d06ab372e7404a8/0d8125f73a1fa9be2a49046c1dddd31f/image.png)

**Comment by avindra** [comment]
@eacevedof not sure about PHP7 support, but see #233 for Composer 2

**Comment by eacevedof** [comment]
> @eacevedof not sure about PHP7 support, but see #233 for Composer 2

Thank you @avindra I was working with no issues till I had to rebuild my containers.

**Comment by eacevedof** [comment]
Issue #233 has the concerning info about this error.

**Comment by avindra** [comment]
Hey @eacevedof  you should try changing the spec to run with the ignore flag:

```sh
composer global require hirak/prestissimo --ignore-platform-reqs
```

This informs composer that you know what you're doing and to ignore any specific PHP engine constraint.

I vaguely remember `Composer1` + `hirak/prestissimo` + `PHP7` working perfectly fine.

The better option is probably to use Composer 2 and uninstall prestissimo.

In any case, the latest release should still work well if you really need Composer 1.
