### ISSUE TITLE
Yii2 Advanced App Template doesn't install

### ISSUE THREAD

**Issue by berezuev** [hirak/prestissimo#33]
First, I've installed Laravel, and **prestissimo** worked perfectly.
Then, I've tried to install [Yii2 Advanced App](https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide/start-installation.md). Composer installed npm and bower packages (via [composer-asset-plugin](https://github.com/francoispluchino/composer-asset-plugin/blob/master/Resources/doc/index.md)), but then console stopped as seen on screenshot below:
![image](https://cloud.githubusercontent.com/assets/695546/12712157/4acf068a-c8d7-11e5-95fb-f605307c4a69.png)
It has already passed 30 minutes, but nothing happend...

**Comment by nikhil-pandey** [comment]
@berezuev Could you run the command again with -vvv flag and share the output

**Comment by nikhil-pandey** [comment]
Seems like composer-asset-plugin is crossing github's rate limit and is requiring an oauth token. Also composer-asset-plugin is downloading a lot of files on single thread and taking a lot of time to complete. For me it took 15 minutes to complete the installation, there wasn't any issue.

Doesn't seem like issue with prestissimo.

**Comment by berezuev** [comment]
I forget to stop installation, and it still stopped on same position (after 3 hours).
I stopped via "CTRL+C", and console showed me this error:
![image](https://cloud.githubusercontent.com/assets/695546/12715950/50cc2df8-c8ee-11e5-8740-bc5a3e2ef806.png)

Installing with -vvv key works perfectly

**Comment by nikhil-pandey** [comment]
@berezuev Do a thing. Enable verbose for prestissimo.

Run the command again and save the output to a file
```
composer create-project yiisoft/yii2-app-advanced test -vvv --profile --prefer-dist > logfile
```
And post the whole log here please.

**Comment by berezuev** [comment]
@nikhil-pandey [Here](https://gist.github.com/berezuev/2fe38243ef11231f2bd5) is a logfile, and [here](https://gist.github.com/berezuev/d46d4b37514e818fe312) I've added a real console output

**Comment by nikhil-pandey** [comment]
I see no error in those files.

**Comment by berezuev** [comment]
Oh. Really, now it works. 
If I reproduce this error again, I'll post log here

**Comment by hirak** [comment]
@berezuev Could you tell me your prestissimo's version ?

```bash
$ composer global show -i
```

**Comment by berezuev** [comment]
@hirak 
```
fxp/composer-asset-plugin v1.1.1 NPM/Bower Dependency Manager for Composer
hirak/prestissimo         0.1.7  composer parallel install plugin
```

**Comment by nikhil-pandey** [comment]
@hirak The problem has been solved. I think you should close this.

**Comment by hirak** [comment]
@berezuev 
I think this problem is the same as: 
https://travis-ci.org/hirak/prestissimo/jobs/106261923

I tagged 0.1.8. Please update. 

```bash
$ composer global update hirak/prestissimo
```
https://github.com/hirak/prestissimo/commit/3a9ecbf1ce8eda159dec46bc6dc481ea583d3459

@nikhil-pandey Thank you !
