### ISSUE TITLE
Using within docker container hangs

### ISSUE THREAD

**Issue by andrewmclagan** [hirak/prestissimo#38]
When `composer install --prefer-dist --no-interaction` within a docker container. This pluggin causes composer to hang at various, random, points.

I have tried it under a number of configurations and all hang, occasionally working.

Although a normal docker install without the plugin works fine.

**Comment by joelwurtz** [comment]
This may be related to this error : https://github.com/docker/docker/issues/18180, are you on aufs ?

**Comment by andrewmclagan** [comment]
Yeah on `aufs`, have to wait for the Debian fix. :-(

sad face.

**Comment by joelwurtz** [comment]
You can up the number of cpu also, or use the overlay driver if you have a kernel up to date (which works great, using it for some months)

**Comment by andrewmclagan** [comment]
Im working on OSX and already have 4 cpu's deletegated to the virtualbox driver

**Comment by rajanvalecha12** [comment]
For me this worked after i disabled xdebug by commenting

> XDEBUG_ENABLED=1

inside docksal.env file

**Comment by sinamiandashti** [comment]
for me it was --no-plugin shit flag in composer install
