### ISSUE TITLE
Errors with prestissimo

### ISSUE THREAD

**Issue by Rhymond** [hirak/prestissimo#40]
Some errors with prestissimo, after remove it everything works fine.
Screenshot: http://puu.sh/mUroj/616f04d713.png

> Loading composer repositories with package information
Installing dependencies (including require-dev)

>   [Seld\JsonLint\ParsingException]
>   "https://bower.herokuapp.com/packages/metismenu" does not contain valid JSON
>   Parse error on line 1:
>   Package not found
>   ^
>   Expected one of: 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '['
> 
> 
> install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...
> 
> vagrant@scotchbox:/var/www/sirena$ sudo composer global remove hirak/prestissimo
>

**Comment by hirak** [comment]
@Rhymond Could you tell me your prestissimo's version?
```bash
$ composer global show -i
```

If you used composer-asset-plugin, Please try new version: prestissimo-0.1.9. I tweaked the logic for auto-cleaning garbage files.

```bash
$ composer global update hirak/prestissimo
```

**Comment by hirak** [comment]
I think that is not a bug in prestissimo.

>  "https://bower.herokuapp.com/packages/metismenu" does not contain valid JSON
