### ISSUE TITLE
proc_open(): fork failed - Cannot allocate memory

### ISSUE THREAD

**Issue by jumper423** [hirak/prestissimo#56]
Using version ^0.1.12 for hirak/prestissimo
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing hirak/prestissimo (0.1.12)
    Downloading: 100%         
The following exception is caused by a lack of memory and not having swap configured
Check https://getcomposer.org/doc/articles/troubleshooting.md#proc-open-fork-failed-errors for details
The following exception is caused by a lack of memory and not having swap configured
Check https://getcomposer.org/doc/articles/troubleshooting.md#proc-open-fork-failed-errors for details
PHP Fatal error:  Uncaught exception 'ErrorException' with message 'proc_open(): fork failed - Cannot allocate memory' in phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:940
Stack trace:
#0 [internal function]: Composer\Util\ErrorHandler::handle(2, 'proc_open(): fo...', 'phar:///usr/loc...', 940, Array)
#1 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(940): proc_open('stty -a | grep ...', Array, NULL, NULL, NULL, Array)
#2 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(748): Symfony\Component\Console\Application->getSttyColumns()
#3 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(709): Symfony\Component\Console\Application->getTerminalDimensions()
#4 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(639): Symfony\Component\Console\Application->getTerminalWidth()
#5 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(231): Symfony\Component\Console\Application->renderException(Object(ErrorException), Ob in phar:///usr/local/bin/composer/vendor/symfony/console/Application.php on line 940

Fatal error: Uncaught exception 'ErrorException' with message 'proc_open(): fork failed - Cannot allocate memory' in phar:///usr/local/bin/composer/vendor/symfony/console/Application.php on line 940

ErrorException: proc_open(): fork failed - Cannot allocate memory in phar:///usr/local/bin/composer/vendor/symfony/console/Application.php on line 940

Call Stack:
    0.0004     223440   1. {main}() /usr/local/bin/composer:0
    0.0480     408808   2. require('phar:///usr/local/bin/composer/bin/composer') /usr/local/bin/composer:25
    0.1498    3767264   3. Composer\Console\Application->run() phar:///usr/local/bin/composer/bin/composer:43
    0.1668    4119528   4. Symfony\Component\Console\Application->run() phar:///usr/local/bin/composer/src/Composer/Console/Application.php:98
   73.8030  208712688   5. Composer\Console\Application->renderException() phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:127
   73.8038  208712864   6. Symfony\Component\Console\Application->renderException() phar:///usr/local/bin/composer/src/Composer/Console/Application.php:231
   73.8039  208713216   7. Symfony\Component\Console\Application->getTerminalWidth() phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:639
   73.8039  208713216   8. Symfony\Component\Console\Application->getTerminalDimensions() phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:709
   73.8039  208713216   9. Symfony\Component\Console\Application->getSttyColumns() phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:748
   73.8039  208715176  10. proc_open() phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:940
   73.8045  208716312  11. Composer\Util\ErrorHandler::handle() phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:940

**Comment by hirak** [comment]
Please read the documentation. This is not a bug.
https://getcomposer.org/doc/articles/troubleshooting.md#proc-open-fork-failed-errors

**Comment by tarunkflexsin** [comment]
fafadsfd
