### ISSUE TITLE
Composer can't reach CAfile anymore

### ISSUE THREAD

**Issue by mazedlx** [hirak/prestissimo#57]
When using self-signed certificates and prestissimo, composer (or curl to be exact) is no longer able to reach the specifiied CAfile:
`error setting certificate verify locations:
  CAfile: /home/cleo/.gitcerts/
  CApath: none:77
https://packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date
`

**Comment by hirak** [comment]
Sorry, this is my mistake.
I'll fix soon.

**Comment by hirak** [comment]
@mazedlx Please try prestissimo-0.1.14 and `cainfo` option. `capath` option didn't work well.

```json
"config": {
  "prestissimo": {
    ...
    "cainfo": "/absolute/path/to/cacert.pem",
    ...
  }
}
```

**Comment by mazedlx** [comment]
I've tried that, to no avail. Error msg is still the same, here's the correspondig composer.json

` "config": {
    "prestissimo": {
        "cainfo": "/etc/pki/tls/certs/bakpem.pem"
    }
}
`

**Comment by mazedlx** [comment]
I've tried that, but to no avail. The error message stays the same. Here's my ~/.composer/composer.json
 ```
{
    "require": {
        "laravel/installer": "^1.3",
        "fabpot/php-cs-fixer": "^1.11",
        "phpunit/phpunit": "^5.1",
        "hirak/prestissimo": "^0.1.14"
    },
    "config": {
        "prestissimo": {
            "cainfo": "/home/cleo/.gitcerts/bak.pem"
        }
    }
}

```

**Comment by hirak** [comment]
@mazedlx Does `bak.pem` contains your cert only ?  It must contains all certs.
https://curl.haxx.se/docs/caextract.html

```bash
$ curl https://curl.haxx.se/ca/cacert.pem >> /home/cleo/.gitcerts/bak.pem
```

**Comment by mazedlx** [comment]
`bak.pem`does only contain my cert. For e.g. Git nothing more is needed. Curl'ed all other certs into my certfile, and guess what:
`error setting certificate verify locations: CAfile: /home/cleo/.gitcerts/ CApath: none:77 https://packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date`

maybe something else is the problem.

**Comment by mazedlx** [comment]
Now that it recognizes composer options, this got fixed. Thanks!
