### ISSUE TITLE
github.com vs codeload.github.com downloads

### ISSUE THREAD

**Issue by barryvdh** [hirak/prestissimo#65]
I see you convert the Github API to a codeload url. Is that to prevent API rate limits or just an unneeded redirect? Wouldn't it be more reliable to use the github.com direct download link instead? Like in https://github.com/composer/composer/pull/4737 ?

```php
if (isset($urls[0]) && preg_match('#^https://api\.github\.com/repos/([^/]++/[^/]++)/zipball/(.++)$#', $urls[0], $match) && !$this->io->hasAuthentication('github.com')) {
            array_unshift($urls, 'https://github.com/'.$match[1].'/archive/'.$match[2].'.zip');
            $processUrl = false;
        }
```

**Comment by hirak** [comment]
Because it needs not to redirect. It's a secondary effect that prestissimo reduces API requests.

Redirect + HTTPS is TERRIBLE slow. So I reduced redirects.
For speed, it's no sense to download directly from https://github.com . It still occures one redirect.

```
https://github.com/hirak/prestissimo/archive/1fdeea0d6b899cfe158bda86ea11bb625685ad15.zip
↓ redirect
https://codeload.github.com/hirak/prestissimo/zip/1fdeea0d6b899cfe158bda86ea11bb625685ad15
```

```
https://api.github.com/repos/hirak/prestissimo/zipball/1fdeea0d6b899cfe158bda86ea11bb625685ad15
↓ redirect
https://codeload.github.com/hirak/prestissimo/legacy.zip/1fdeea0d6b899cfe158bda86ea11bb625685ad15
```

**Comment by hirak** [comment]
Have you solved the problem ? If you find any question, please re-open.
