### ISSUE TITLE
Usage with non-root user

### ISSUE THREAD

**Issue by mavci** [hirak/prestissimo#71]
I want to use this with non-root user. But it didn't work.
I have to be root to use this. How can I work with this package with non-root user?

I'm running composer install with sudo like that `sudo -u myuser composer install`

**Comment by hirak** [comment]
@mavci You can change $COMPOSER_HOME.
https://getcomposer.org/doc/03-cli.md#composer-home

```bash
$ echo 'export COMPOSER_HOME=/path/to/your/writable/directory' > ~/.bashrc
$ composer global require 'hirak/prestissimo'
```

**Comment by mavci** [comment]
Thanks it's worked.
