### ISSUE TITLE
Failed to connect to packagist.org port 80

### ISSUE THREAD

**Issue by koriym** [hirak/prestissimo#73]
<img width="933" alt="2016-04-03 4 10 07" src="https://cloud.githubusercontent.com/assets/529021/14228536/06e4cd1e-f952-11e5-88ae-ce71f5a00e0a.png">

This exception is thrown sometimes. (not always)
But the problem is immediately gone after remove `prestissimo`.  I couldn't figure out the reason or condition.

**Comment by arianmaykon** [comment]
Same problem here on Linux Mint 17 (64 bits) and php 5.6.
But on my Macbook it works fine

**Comment by hirak** [comment]
Please let me know again when reproduced.
