### ISSUE TITLE
Class 'GitHubRequest' not found when installing on Windows

### ISSUE THREAD

**Issue by Veve2** [hirak/prestissimo#74]
While trying to install prestissimo on Windows 7, I've got this error:

> composer global require hirak/prestissimo
> Changed current directory to C:/Users/HERVE/AppData/Roaming/Composer
> Using version ^0.1.18 for hirak/prestissimo
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
>   - Removing hirak/prestissimo (0.1.10)
>   - Installing hirak/prestissimo (0.1.18)
> 
> Fatal error: Class 'Hirak\Prestissimo\Aspects\GitHubRequest' not found in C:\Users\Veve2\AppData\Roaming\Composer\vendor\hirak\prestissimo\src\Factory.php on li                                                       ne 79
>

**Comment by hirak** [comment]
@Veve2 Updates of composer plugin will occasionally fail. Please try 'remove' and re-'require'.

```powershell
> composer global remove 'hirak/prestissimo' --no-plugins
> composer global require 'hirak/prestissimo'
```

**Comment by Veve2** [comment]
`composer global remove 'hirak/prestissimo' --no-plugins` didn't worked, 

> The requested package hirak/prestissimo == 0.1.10.0 could not be found.

I've edited the global composer.json, removed the entry about prestissimo, then used `composer global require "hirak/prestissimo":"0.1.18"` to install it.

**Comment by hirak** [comment]
In prestissimo-3.0.0, `GitHubRequest` class  has removed. Please update.
