### ISSUE TITLE
"Failed to download ... from dist ... not a zip archive"

### ISSUE THREAD

**Issue by teohhanhui** [hirak/prestissimo#78]
```
    Failed to download ... from dist: ... is not a zip archive.
Failed to execute unzip ...

unzip: unexpected end of file
unzip: inflate error
```

I get this sometimes. Not sure how to reproduce...

**Comment by hirak** [comment]
If you reproduce it, Please report it again.

**Comment by teohhanhui** [comment]
Do we fall back to the normal dist download if the downloaded zip archive is unusable?

**Comment by hirak** [comment]
@teohhanhui Yes. (since prestissimo >= 3.0.0)

**Comment by teohhanhui** [comment]
I think you meant >= 0.3.0

Thanks!
