### ISSUE TITLE
Enable work with HHVM

### ISSUE THREAD

**Issue by hirak** [hirak/prestissimo#8]
https://twitter.com/ex_takezawa/status/687976776794939393

**Comment by DQNEO** [comment]
I reproduced it.

```
[root@e851e14a7945 tmp1]# hhvm --version
HipHop VM 3.10.1 (rel)
Compiler: tags/HHVM-3.10.1-0-g689b4969a141620ee5a282ce0dbf72278c84d44b
Repo schema: 6c99ee1f98340f6f3ef397a332583f0e843a627d
[root@e851e14a7945 tmp1]# composer require -v symfony/symfony
Using version ^3.0 for symfony/symfony
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
    Prefetch start: success: 0, failure: 0, total: 15
```

the terminal freezes right after ` Prefetch start`.

I used this docker image https://hub.docker.com/r/dqneo/hhvm/

**Comment by holyshared** [comment]
@DQNEO It was not a problem that it is **3.11.0**
I think better to upgrade is good.

	HipHop VM 3.11.0 (rel)
	Compiler: tags/HHVM-3.11.0-0-g3dd564a8cde23e3205a29720d3435c771274085e
	Repo schema: 52047bdda550f21c2ec2fcc295e0e6d02407be51

**Comment by DQNEO** [comment]
Sounds Gool!

**Comment by hirak** [comment]
I reproduced at 3.11.0 too.

```bash
$ brew tap hhvm/hhvm
$ brew install hhvm
...
$ hhvm --version
HipHop VM 3.11.0 (rel)
Compiler: 1453002337_N
Repo schema: 09bbfd9c98f0482ec2759967ae6ffa0f68d54fa6

$ uname -a
Darwin hiraku.lan 15.2.0 Darwin Kernel Version 15.2.0: Fri Nov 13 19:56:56 PST 2015; root:xnu-3248.20.55~2/RELEASE_X86_64 x86_64
```

@holyshared Could you tell me your OS version?

**Comment by holyshared** [comment]
@hirak

My environment is Debian Jessie 8.1.0(Vagrant).

	vagrant@debian:~$ uname -a
	Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1 (2015-05-24) x86_64 GNU/Linux

	vagrant@debian:~$ hhvm --version
	HipHop VM 3.11.0 (rel)
	Compiler: tags/HHVM-3.11.0-0-g3dd564a8cde23e3205a29720d3435c771274085e
	Repo schema: 52047bdda550f21c2ec2fcc295e0e6d02407be51

**Comment by ytake** [comment]
:+1: awesome!
