### ISSUE TITLE
Support for composer 1.1

### ISSUE THREAD

**Issue by mrtnsn** [hirak/prestissimo#87]
Any plans for composer 1.1 support?

**Comment by schmunk42** [comment]
@mrtnsn I had `0.1.18` of this plugin, which does not work with composer 1.1, but `0.2.3` works for me.

**Comment by andrey-helldar** [comment]
From console:

> The "hirak/prestissimo" plugin was skipped because it requires a Plugin API version ("~1.0.0-alpha10") that does not match your Composer installation ("1.1.0"). You may need to run composer update with the "--no-plugins" option.

Waiting new version :)

**Comment by mrtnsn** [comment]
@schmunk42 thanks, that fixed it :)
