### ISSUE TITLE
Self Signed Certificate

### ISSUE THREAD

**Issue by EAnushan** [hirak/prestissimo#9]
I'm using a local instance of toranproxy with a self signed certificate. I get the following error when running `composer update`.

`SSL certificate problem: self signed certificate:60`

My .composer/config.json looks like this:

```
{
    "config": {
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://toran.local/repo/private/",
            "options": {
                "ssl": {
                    "allow_self_signed": true
                }
            }
        }
    ]
}
```

I've allowed self signed certificates here, and it works fine without the plugin. I'm assuming this option needs to be forwarded to the cURL handler that does the prefetching.

**Comment by JLMorales** [comment]
I get the same SSL error with the following composer.json file:
```
{
    "config": {
		"vendor-dir": "include/vendor",
		"prestissimo": {
            "maxConnections": 6,
            "minConnections": 3,
            "pipeline": false,
            "verbose": true
        }
	},
	"autoload": {
		"classmap": [
		  "include/libreria/"
		]
    },
	"require": {
		"hautelook/phpass": "0.3.0",
		"phpmailer/phpmailer": "v5.2.6",
		"xuanyan/database": "dev-master",
		"facebook/php-sdk-v4" : "4.0.*",
		"soup/paginator": "1.0.4",
		"twig/twig": "1.*",
		"jv2222/ezsql_version": "dev-master",
		"mobiledetect/mobiledetectlib": "dev-master",
		"guzzlehttp/guzzle": "5.0.*@dev",
		"anlutro/curl": "dev-master",
		"illuminate/database": "~5.0",
		"symfony/var-dumper": "3.0.*@dev",
        "hyyan/jaguar": "1.0.*",
		"slim/slim": "2.2.0"
    }
}
```

**Comment by hirak** [comment]
It's difficult to fix. But I can create new option for the solution.

```json
{
  "config": {
    "prestissimo": {
      "insecure": true,
      "capath": "/absolute/path/to/cacert.pem"
    }
  }
}
```

### insecure (bool)
* default: false

If insecure is true, this plugin doesn't verify all https certs. (CURLOPT_VERIFYPEER is off)
You should not change this option.

### capath (string)
* default: "" (empty)

path to cacert.pem

**Comment by hirak** [comment]
@EAnushan @JLMorales I released v0.1.5.
Please try it.

```bash
$ composer global remove hirak/prestissimo
$ composer global install hirak/prestissimo
```

**Comment by EAnushan** [comment]
The new options seem to work just fine. Thank you!

**Comment by JLMorales** [comment]
Thanks for the update!  I can also confirm it. I'm converting everyone at the office when they saw just how fast this is. :) Envy. The best marketing tool. LOL
