### ISSUE TITLE
incompatible to composer 1.1.0

### ISSUE THREAD

**Issue by tolry** [hirak/prestissimo#90]
First of all: thanks for this plugin, a real time saver!

After upgrading to composer 1.1.0 I got the following error
> The "hirak/prestissimo" plugin was skipped because it requires a Plugin API version ("~1.0.0-alpha10") that does not match your Composer installation ("1.1.0").

This is probably just due to a wrong version constraint, `^1.0.0` might just work without any additional changes?

If I can help solving this, give me hint.

**Comment by xabbuh** [comment]
Did you try one of the 0.2.x versions of the plugin?

**Comment by sebastiaanluca** [comment]
Try running `composer global remove hirak/prestissimo --no-plugins && composer global require hirak/prestissimo` to remove and reinstall it.

**Comment by andrey-helldar** [comment]
@sebastiaanluca 
It's work!)
Thanks!

**Comment by arifr007** [comment]
@sebastiaanluca whooooa thanks you solve my problem >_<

**Comment by tolry** [comment]
@sebastiaanluca @xabbuh thanks, got it working with 0.2.x

Just for the record, alternatively you could simply bump the prestissimo version using

`composer require hirak/prestissimo '^0.2' --no-plugins`
